
package resultgenerationsystems;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


public class OperatorMarksEntry extends javax.swing.JFrame {

    /**
     * Creates new form OperatorMarksEntry
     */
    public OperatorMarksEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rollTextField = new javax.swing.JTextField();
        regTextField = new javax.swing.JTextField();
        fatherTextField = new javax.swing.JTextField();
        motherTextField = new javax.swing.JTextField();
        instituteTextField = new javax.swing.JTextField();
        boardTextField = new javax.swing.JTextField();
        groupTextField = new javax.swing.JTextField();
        DOBTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        codeComboBox = new javax.swing.JComboBox<>();
        nameComboBox = new javax.swing.JComboBox<>();
        mcqTextField = new javax.swing.JTextField();
        practicalTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        theoryTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        gpaTextPane = new javax.swing.JTextPane();
        exam_typeComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new javax.swing.JComboBox<>();
        ToggleButton = new javax.swing.JToggleButton();
        boardSelect = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Roll no.");

        jLabel4.setText("Reg no");

        jLabel5.setText("Father's Name");

        jLabel6.setText("Mother's Name");

        jLabel7.setText("Board");

        jLabel8.setText("Group");

        jLabel9.setText("DATE OF BIRTH");

        jLabel10.setText("Name Of Institute");

        rollTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollTextFieldActionPerformed(evt);
            }
        });

        regTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("NAME");

        codeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT AN OPTION", "101", "102", "107", "108", "109", "150", "111", "136", "137", "138", "147", "154", "156", "126" }));
        codeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeComboBoxActionPerformed(evt);
            }
        });

        nameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT AN OPTION", "BANGLA-|", "BANGLA-||", "ENGLISH-|", "ENGLISH-||", "MATHEMATICS", "BANGLADESH AND GLOBAL STUDIES", "ISLAM AND MORAL EDUCATION", "PHYSICS", "CHEMISTRY", "BIOLOGY", "PHYSICAL EDUCATION & SPORTS", "INFORMATION AND COMMUNICATION TECHNOLOGY", "CAREER EDUCATION ", "HIGHER MATHEMATICS" }));

        jLabel11.setText("SUBJECT CODE");

        jLabel12.setText("SUBJECT NAME");

        jLabel13.setText("THEORY");

        jLabel14.setText("MCQ");

        jLabel15.setText("PRACTICAL");

        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        viewButton.setText("VIEW");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SUBJECT CODE", "SUBJECT NAME", "THEORY", "MCQ", "PRACTICAL"
            }
        ));
        jScrollPane1.setViewportView(Table);

        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("GPA");

        jScrollPane2.setViewportView(gpaTextPane);

        exam_typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an exam type", "JSC/JDC/EQUIVALENT", "JSC/JDC", "SSC/DAKHIL", "HSC/ALIM", "DIPLOMA IN COMMERCE", "DIPLOMA IN BUSINESS STUDIES" }));
        exam_typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exam_typeComboBoxActionPerformed(evt);
            }
        });

        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Exam year", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008" }));

        ToggleButton.setText("Go To Show Result");
        ToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButtonActionPerformed(evt);
            }
        });

        boardSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select an Board", "DHAKA", "CHITTAGONG" }));

        jToggleButton1.setText("ADD STUDENT");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jButton1)
                        .addGap(86, 86, 86)
                        .addComponent(jButton2)
                        .addGap(164, 164, 164)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(codeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(nameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(theoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(mcqTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(practicalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel17))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(174, 174, 174)
                                        .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(boardSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nameTextField)
                                            .addComponent(regTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel2))
                                                .addGap(40, 40, 40)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(fatherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(motherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(exam_typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(DOBTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(groupTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(boardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(instituteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(searchButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(40, 40, 40)
                                .addComponent(rollTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(1039, 1039, 1039))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jToggleButton1)
                .addGap(126, 126, 126)
                .addComponent(ToggleButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ToggleButton)
                            .addComponent(jToggleButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exam_typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boardSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rollTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(searchButton))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(regTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fatherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(motherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(codeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel15))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(mcqTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(practicalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(theoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(instituteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel7)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(groupTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(DOBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(viewButton)))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public int calculateFullMarks(String theory , String mcq , String practical)
    {
               String a = "0";
               String b = "0";
               String c ="0";
              
               if(theory!=null&& theory.length() > 0){a = theory;}
               if(mcq!= null&& mcq.length() > 0){ b = mcq;}
               if(practical!=null&& practical.length() > 0){ c = practical;}
               
                double x = Double.parseDouble(a);
                double y = Double.parseDouble(b);
                double z = Double.parseDouble(c);
                int result = (int) Math.ceil(x+y+z);
                return result;
                
          }
    
    public String calculateGPA(int result)
    {
                if(result>=80&&result<=100){return "A+";}
                else if (result>=70&&result<=79){return "A";}
                else if (result>=60&&result<=69){return "A-";}
                else if (result>=50&&result<=59){return "B";}
                else if (result>=40&&result<=49){return "C";}
                else if (result>=33&&result<=39){return "D";}
                else if(result<=32){return "F";}
                else return "error";
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        String roll = rollTextField.getText();
        String reg = regTextField.getText();
        String name = nameTextField.getText();
        String father = fatherTextField.getText();
        String mother = motherTextField.getText();
        String institute = instituteTextField.getText();
        String board = boardTextField.getText();
        String group = groupTextField.getText();
        String DOB = DOBTextField.getText();
        String sub_id = (String)codeComboBox.getSelectedItem();
        String sub_name = (String)nameComboBox.getSelectedItem();
        String theory = theoryTextField.getText();
        String mcq = mcqTextField.getText();
        String practical = practicalTextField.getText();
        String exam_type = (String)exam_typeComboBox.getSelectedItem();
        String exam_year = (String)yearComboBox.getSelectedItem();
        
        
        int full_marks = calculateFullMarks(theory,mcq,practical);
        String GPA = calculateGPA(full_marks);
        String marks = Integer.toString(full_marks);
        System.out.println(marks);
        gpaTextPane.setText(GPA);
        
        
       
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            
          if(board.equals("DHAKA")){
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:xe","saddam","123" );
            Statement stmt = con.createStatement();
            int x = stmt.executeUpdate("insert into subject values('"+sub_id+"','"+sub_name+"','"+marks+"','"+exam_type+"','"+roll+"','"+reg+"','"+theory+"','"+mcq+"','"+practical+"','"+GPA+"','"+exam_year+"')");
            
            if (x > 0){             
                System.out.println("Successfully Inserted"); 
          JOptionPane.showMessageDialog(null,"Successfully Inserted");
            }
            else{            
                System.out.println("Insert Failed"); 
              JOptionPane.showMessageDialog(null,"Insert Failed");

            }
            
            Statement stmt1 = con.createStatement();
            ResultSet rs1 = stmt1.executeQuery("select * from subject where roll_no = '"+roll+"' and reg_no = '"+reg+"' order by sub_id asc");
            
            Table.setModel(DbUtils.resultSetToTableModel(rs1));
          }  
           
          
          if(board.equals("CHITTAGONG")){
            
         
            Connection conChittagong = DriverManager.getConnection(
                "jdbc:oracle:thin:@192.168.43.98:1521:xe","farhan","123");
            Statement stmt = conChittagong.createStatement();
            int x = stmt.executeUpdate("insert into subject values('"+sub_id+"','"+sub_name+"','"+marks+"','"+exam_type+"','"+roll+"','"+reg+"','"+theory+"','"+mcq+"','"+practical+"','"+GPA+"','"+exam_year+"')");
            
            if (x > 0){             
                System.out.println("Successfully Inserted"); 
          JOptionPane.showMessageDialog(null,"Successfully Inserted");
            }
            else{            
                System.out.println("Insert Failed"); 
              JOptionPane.showMessageDialog(null,"Insert Failed");

            }
            
            Statement stmt1 = conChittagong.createStatement();
            ResultSet rs1 = stmt1.executeQuery("select * from subject order by sub_id asc");
            
            Table.setModel(DbUtils.resultSetToTableModel(rs1));
             conChittagong.close();
          }
        }catch(Exception e){
            System.out.println(e);
        }
  
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void regTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regTextFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        
       
        
        try{
             String roll = rollTextField.getText();
             String board = boardSelect.getSelectedItem().toString();
       
            Class.forName("oracle.jdbc.driver.OracleDriver");
            
            
            if(board.equals("DHAKA")){
                
            Connection conDhaka = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:xe","saddam","123");
          
            
            Statement stmt = conDhaka.createStatement();
            
            ResultSet rs = stmt.executeQuery("select * from student,board where student.roll_no ='"+roll+"' and student.roll_no = board.roll_no ");
            //Table.setModel(DbUtils.resultSetToTableModel(rs));
            while(rs.next())
            {
                rollTextField.setText(rs.getString(2));
                regTextField.setText(rs.getString(3));
                nameTextField.setText(rs.getString(4));
                fatherTextField.setText(rs.getString(5));
                motherTextField.setText(rs.getString(6));
                instituteTextField.setText(rs.getString(13));
                boardTextField.setText(rs.getString(11));
                groupTextField.setText(rs.getString(8));
                DOBTextField.setText(rs.getString(7));
            }
           }
            
            else if(board.equalsIgnoreCase("CHITTAGONG")){
                Connection conChittagong = DriverManager.getConnection(
                "jdbc:oracle:thin:@192.168.43.98:1521:xe","farhan","123");
          
            
            Statement stmt = conChittagong.createStatement();
            
            ResultSet rs = stmt.executeQuery("select * from student,board where student.roll_no ='"+roll+"' and student.roll_no = board.roll_no ");
            //Table.setModel(DbUtils.resultSetToTableModel(rs));
            while(rs.next())
            {
                rollTextField.setText(rs.getString(2));
                regTextField.setText(rs.getString(3));
                nameTextField.setText(rs.getString(4));
                fatherTextField.setText(rs.getString(5));
                motherTextField.setText(rs.getString(6));
                instituteTextField.setText(rs.getString(13));
                boardTextField.setText(rs.getString(11));
                groupTextField.setText(rs.getString(8));
                DOBTextField.setText(rs.getString(7));
            }
           
          }
            
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void rollTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollTextFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

      String board = boardTextField.getText();
       
      
      
       DefaultTableModel model = (DefaultTableModel) Table.getModel();
        int selectedRowIndex = Table.getSelectedRow();
            
            String cell = Table.getModel().getValueAt(selectedRowIndex, 0).toString();
            System.out.println(selectedRowIndex);
            System.out.println(cell);
        try
        {
            
            Class.forName("oracle.jdbc.driver.OracleDriver"); 
            
            if(board.equalsIgnoreCase("Dhaka")){
            
            Connection con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "saddam", "123"); 
            Statement stmt = con.createStatement(); 
                   
            // Deleting from database 
            String q1 = "DELETE from subject WHERE sub_id = "+cell; 
                      
            int x = stmt.executeUpdate(q1); 
              
            if (x > 0)             {
                System.out.println("One User Successfully Deleted");             
            JOptionPane.showMessageDialog(null,"One data Successfully Deleted");
            }else{
                System.out.println("ERROR OCCURED ");
                JOptionPane.showMessageDialog(null,"ERROR OCCURED");
            }
          }
       
            else if(board.equalsIgnoreCase("Chittagong")){
                 Connection con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@192.168.43.98:1521:xe", "farhan", "123"); 
            Statement stmt = con.createStatement(); 
                   
            // Deleting from database 
            String q1 = "DELETE from subject WHERE sub_id = "+cell; 
                      
            int x = stmt.executeUpdate(q1); 
              
            if (x > 0)             {
                System.out.println("One User Successfully Deleted");             
            JOptionPane.showMessageDialog(null,"One data Successfully Deleted");
            }else{
                System.out.println("ERROR OCCURED ");
                JOptionPane.showMessageDialog(null,"ERROR OCCURED");
            }
            
            
         }
            
        }catch(Exception e){
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
         try{
             
            String roll = rollTextField.getText();
            String board = boardTextField.getText();
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            
            if(board.equalsIgnoreCase("Dhaka")){
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:xe","saddam","123");
            Statement stmt1 = con.createStatement();
            ResultSet rs1 = stmt1.executeQuery("select * from subject where roll_no = '"+roll+"' order by sub_id asc");
            
            Table.setModel(DbUtils.resultSetToTableModel(rs1));
            
            }
             
            else if(board.equalsIgnoreCase("Chittagong")){
                
               Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@192.168.43.98:1521:xe","farhan","123");
            Statement stmt1 = con.createStatement();
            ResultSet rs1 = stmt1.executeQuery("select * from subject where roll_no = '"+roll+"' order by sub_id asc");
            
            Table.setModel(DbUtils.resultSetToTableModel(rs1));
            
 
            }
            
        }catch(Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_viewButtonActionPerformed

    private void codeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeComboBoxActionPerformed

    private void ToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButtonActionPerformed
       new StudentShowResult().setVisible(true);
    }//GEN-LAST:event_ToggleButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void exam_typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exam_typeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exam_typeComboBoxActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       new studentBoardRegistration().setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperatorMarksEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperatorMarksEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperatorMarksEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperatorMarksEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperatorMarksEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOBTextField;
    private javax.swing.JTable Table;
    private javax.swing.JToggleButton ToggleButton;
    private javax.swing.JComboBox<String> boardSelect;
    private javax.swing.JTextField boardTextField;
    private javax.swing.JComboBox<String> codeComboBox;
    private javax.swing.JComboBox<String> exam_typeComboBox;
    private javax.swing.JTextField fatherTextField;
    private javax.swing.JTextPane gpaTextPane;
    private javax.swing.JTextField groupTextField;
    private javax.swing.JTextField instituteTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField mcqTextField;
    private javax.swing.JTextField motherTextField;
    private javax.swing.JComboBox<String> nameComboBox;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField practicalTextField;
    private javax.swing.JTextField regTextField;
    private javax.swing.JTextField rollTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField theoryTextField;
    private javax.swing.JButton viewButton;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables
}
