/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resultgenerationsystems;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Zahid Ahmed
 */
public class studentBoardRegistration extends javax.swing.JFrame {

    /**
     * Creates new form studentBoardRegistration
     */
    public studentBoardRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rollTextField = new javax.swing.JTextField();
        regTextField = new javax.swing.JTextField();
        fatherTextField = new javax.swing.JTextField();
        motherTextField = new javax.swing.JTextField();
        instituteTextField = new javax.swing.JTextField();
        groupTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        mobileTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        EIINTextField = new javax.swing.JTextField();
        boardIDComboBox = new javax.swing.JComboBox<>();
        boardNameComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        ToggleButton = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rollTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollTextFieldActionPerformed(evt);
            }
        });

        regTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("NAME");

        jLabel3.setText("Roll no.");

        jLabel4.setText("Reg no");

        jLabel5.setText("Father's Name");

        jLabel6.setText("Mother's Name");

        jLabel8.setText("Group");

        jLabel9.setText("DATE OF BIRTH");

        jLabel10.setText("Name Of Institute");

        jLabel1.setText("Mobile ");

        jLabel11.setText("EIIN");

        boardIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT BOARD ID ", "DHK", "CHV" }));

        boardNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT YOUR BOARD", "DHAKA", "CHITTAGONG" }));

        jLabel14.setText("Student Registration Form ");

        jButton1.setText("Add the student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("View");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table);

        jButton5.setText("DELETE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        ToggleButton.setText("Go To Show Result");
        ToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButtonActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Go to Marks entry");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jToggleButton1)
                                .addGap(29, 29, 29)
                                .addComponent(ToggleButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nameTextField)
                                            .addComponent(regTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel2))
                                                .addGap(40, 40, 40)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(fatherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(motherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(40, 40, 40)
                                                .addComponent(rollTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel6))
                                .addGap(33, 33, 33)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(instituteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EIINTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(61, 61, 61)
                                        .addComponent(groupTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(boardIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(boardNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(mobileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jButton1)
                        .addGap(97, 97, 97)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ToggleButton)
                        .addComponent(jToggleButton1)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(regTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fatherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(motherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(EIINTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(instituteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(groupTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boardIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boardNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(mobileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(370, 370, 370))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollTextFieldActionPerformed

    private void regTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String roll = rollTextField.getText();
            String reg = regTextField.getText();
            String name = nameTextField.getText();
            String father = fatherTextField.getText();
            String mother = motherTextField.getText();
            String EIIN = EIINTextField.getText();
            String institute = instituteTextField.getText();
            String group = groupTextField.getText();
            String dob = dateChooserCombo1.getText();
            String mobile = mobileTextField.getText();
            String boardID = boardIDComboBox.getSelectedItem().toString();
            String board = boardNameComboBox.getSelectedItem().toString();
            System.out.println(dob);
             try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            
          if(board.equals("DHAKA")){
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:xe","saddam","123" );
            Statement stmt = con.createStatement();
            Statement stmt1 = con.createStatement();
                int x = stmt.executeUpdate("insert into student values(serial_no.nextval,'"+roll+"','"+reg+"','"+name+"','"+father+"','"+mother+"','"+group+"','"+mobile+"','"+dob+"')");
                int y = stmt1.executeUpdate("insert into board values('"+boardID+"','"+board+"','"+EIIN+"','"+institute+"','"+roll+"','"+reg+"')");
            if (x > 0&&y>0){             
                System.out.println("Successfully Inserted"); 
          JOptionPane.showMessageDialog(null,"Successfully Inserted");
            }
            else{            
                System.out.println("Insert Failed"); 
              JOptionPane.showMessageDialog(null,"Insert Failed");

            }
            
            Statement stmt2 = con.createStatement();
            ResultSet rs1 = stmt2.executeQuery("select * from student");
            
            Table.setModel(DbUtils.resultSetToTableModel(rs1));
          }  
          
          
          if(board.equals("CHITTAGONG")){
            
         
            Connection conChittagong = DriverManager.getConnection(
                "jdbc:oracle:thin:@192.168.43.98:1521:xe","farhan","123");
            Statement stmt = conChittagong.createStatement();
            int x = stmt.executeUpdate("insert into student values(serial_no.nextval,'"+roll+"','"+reg+"','"+name+"','"+father+"','"+mother+"','"+dob+"','"+group+"','"+mobile+"')");
            
            if (x > 0){             
                System.out.println("Successfully Inserted"); 
          JOptionPane.showMessageDialog(null,"Successfully Inserted");
            }
            else{            
                System.out.println("Insert Failed"); 
              JOptionPane.showMessageDialog(null,"Insert Failed");

            }
            
            Statement stmt1 = conChittagong.createStatement();
            ResultSet rs1 = stmt1.executeQuery("select * from subject order by sub_id asc");
            
            Table.setModel(DbUtils.resultSetToTableModel(rs1));
             conChittagong.close();
          }
          
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      
         try{
             
            String roll = rollTextField.getText();
            String reg = regTextField.getText();
            String board = boardNameComboBox.getSelectedItem().toString();
           
            if(board == null){JOptionPane.showMessageDialog(null, "you must have to enter  board name");}
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            
            if(board.equalsIgnoreCase("Dhaka")){
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:xe","saddam","123");
            Statement stmt1 = con.createStatement();
            ResultSet rs1 = stmt1.executeQuery("select * from student where roll_no = '"+roll+"'and reg_no = '"+reg+"'");
            
            Table.setModel(DbUtils.resultSetToTableModel(rs1));
            
            }
             
            else if(board.equalsIgnoreCase("Chittagong")){
                
               Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@192.168.43.98:1521:xe","farhan","123");
            Statement stmt1 = con.createStatement();
            ResultSet rs1 = stmt1.executeQuery("select * from subject where roll_no = '"+roll+"' ");
            
            Table.setModel(DbUtils.resultSetToTableModel(rs1));
            
 
            }
           
            
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        String board = boardNameComboBox.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        int selectedRowIndex = Table.getSelectedRow();

        String cell = Table.getModel().getValueAt(selectedRowIndex, 0).toString();
        System.out.println(selectedRowIndex);
        System.out.println(cell);
        try
        {

            Class.forName("oracle.jdbc.driver.OracleDriver");

            if(board.equalsIgnoreCase("Dhaka")){

                Connection con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "saddam", "123");
                Statement stmt = con.createStatement();

                // Deleting from database
                String q1 = "DELETE from subject WHERE sub_id = "+cell;

                int x = stmt.executeUpdate(q1);

                if (x > 0)             {
                    System.out.println("One User Successfully Deleted");
                    JOptionPane.showMessageDialog(null,"One data Successfully Deleted");
                }else{
                    System.out.println("ERROR OCCURED ");
                    JOptionPane.showMessageDialog(null,"ERROR OCCURED");
                }
            }

            else if(board.equalsIgnoreCase("Chittagong")){
                Connection con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@192.168.43.98:1521:xe", "farhan", "123");
                Statement stmt = con.createStatement();

                // Deleting from database
                String q1 = "DELETE from subject WHERE sub_id = "+cell;

                int x = stmt.executeUpdate(q1);

                if (x > 0)             {
                    System.out.println("One User Successfully Deleted");
                    JOptionPane.showMessageDialog(null,"One data Successfully Deleted");
                }else{
                    System.out.println("ERROR OCCURED ");
                    JOptionPane.showMessageDialog(null,"ERROR OCCURED");
                }

            }

        }catch(Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void ToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButtonActionPerformed
        new StudentShowResult().setVisible(true);
    }//GEN-LAST:event_ToggleButtonActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        new OperatorMarksEntry().setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentBoardRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentBoardRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentBoardRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentBoardRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentBoardRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EIINTextField;
    private javax.swing.JTable Table;
    private javax.swing.JToggleButton ToggleButton;
    private javax.swing.JComboBox<String> boardIDComboBox;
    private javax.swing.JComboBox<String> boardNameComboBox;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JTextField fatherTextField;
    private javax.swing.JTextField groupTextField;
    private javax.swing.JTextField instituteTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField mobileTextField;
    private javax.swing.JTextField motherTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField regTextField;
    private javax.swing.JTextField rollTextField;
    // End of variables declaration//GEN-END:variables
}
