/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resultgenerationsystems;

import java.sql.*;
import java.text.DecimalFormat;
import net.proteanit.sql.DbUtils;

public class StudentFullResult extends javax.swing.JFrame {

    
    
   
    
    
    
    public String calculateGPA(double result)
    {
                if(result==5.0){return "A+";}
                else if (result>=4.00&&result<=4.99){return "A";}
                else if (result>=3.50&&result<=3.99){return "A-";}
                else if (result>=3.00&&result<=3.49){return "B";}
                else if (result>=2.00&&result<=2.99){return "C";}
                else if (result>=1.00&&result<=1.99){return "D";}
                else if(result==0.0){return "F";}
                else return "error";
    }
    
    public StudentFullResult(){
        initComponents();
    }
    
 
    
    public StudentFullResult(String exam , String year , String board, String roll,String reg) {
        initComponents();
        examLabel.setText("Result of "+exam+" EXAMINATION "+year);
        
        yearLabel.setText(year);
        
 
        try{
            
                       
            Class.forName("oracle.jdbc.driver.OracleDriver");
            
           if(board.equalsIgnoreCase("Dhaka")){
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:xe","saddam","123");

           mainWork(con,roll);
            
            
            con.close();
      }
           else if (board.equalsIgnoreCase("Chittagong")){
                Connection conChittagong = DriverManager.getConnection(
                "jdbc:oracle:thin:@192.168.43.98:1521:xe","farhan","123");

                  mainWork(conChittagong,roll);
                  conChittagong.close();
           }
           
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
     public void mainWork(Connection con,String roll){
        try{
            
            Statement stmt1 = con.createStatement();
            ResultSet rs1 = stmt1.executeQuery("select * from student,board where student.roll_no = board.roll_no and student.roll_no = '"+roll+"'");
            
            while(rs1.next()){
                rollLabel.setText(rs1.getString(2));
                nameLabel.setText(rs1.getString(4));
                fatherLabel.setText(rs1.getString(5));
                motherLabel.setText(rs1.getString(6));
                regLevel.setText(rs1.getString(3));
                dobLabel.setText(rs1.getString(7));
                groupLabel.setText(rs1.getString(8));
                instituteLabel.setText(rs1.getString(13));
                boardLabel.setText(rs1.getString(11));
                typeLabel.setText("Regular");
            }
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from subject where roll_no = '"+roll+"'order by sub_id asc");
            
            Table.setModel(DbUtils.resultSetToTableModel(rs));
            Statement stmt2 = con.createStatement();
            ResultSet rs2 = stmt2.executeQuery("select * from subject where roll_no = '"+roll+"'");
            
            double sum = 0.0,GPA = 0.0;
            int count = 0;
            String grade = "";
            while(rs2.next())
            {
                String marks = rs2.getString(10);
                count++;
                if(marks.equals("A+")){GPA = 5.0; grade = "A+";}
                else if (marks.equals("A")){GPA = 4.0; grade = "A";}
                else if (marks.equals("A-")){GPA = 3.5; grade = "A-";}
                else if (marks.equals("B")){GPA = 3.0;grade = "B";}
                else if (marks.equals("C")){GPA = 2.0;grade = "C";}
                else if (marks.equals("D")){GPA = 1.0;grade = "D";}
                else if(marks.equals("F")){GPA = 0.0;grade = "F"; sum = 0; break;}
                
                sum = GPA + sum;
                
            }
            

            double final_gpa= sum/(double)count;
            
            String grades = calculateGPA(final_gpa);
            
            gpaLabel.setText(new DecimalFormat("#.##").format(final_gpa) +   "   Grade: "+ grades);
        }catch(Exception e){
            System.out.println(e);
        }
        }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        groupLabel = new javax.swing.JLabel();
        boardLabel = new javax.swing.JLabel();
        motherLabel = new javax.swing.JLabel();
        fatherLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rollLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        gpaLabel = new javax.swing.JLabel();
        instituteLabel = new javax.swing.JLabel();
        regLevel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        examLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Roll no.");

        jLabel4.setText("NAME");

        jLabel5.setText("Father's Name");

        jLabel6.setText("Mother's Name");

        jLabel7.setText("Board");

        jLabel8.setText("Group");

        jLabel9.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel9.setText("GPA :");

        jLabel10.setText("Name Of Institute");

        jLabel22.setText("YEAR");

        jLabel23.setText("TYPE");

        groupLabel.setText("null");

        boardLabel.setText("null");

        motherLabel.setText("null");

        fatherLabel.setText("null");

        jLabel20.setText("Date Of Birth");

        jLabel21.setText("Registration no");

        rollLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rollLabel.setText("null");

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameLabel.setText("null");

        gpaLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        gpaLabel.setText("null");

        instituteLabel.setText("null");

        regLevel.setText("null");

        dobLabel.setText("null");

        typeLabel.setText("null");

        yearLabel.setText("null");

        jLabel1.setText("SUBJECT WISE GRADE / MARKS ");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Code ", "Subject Name ", "Total Marks", "Grade"
            }
        ));
        Table.setColumnSelectionAllowed(true);
        Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table);
        Table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        examLabel.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        examLabel.setText("null");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(469, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(317, 317, 317))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(308, 308, 308)
                                        .addComponent(jLabel16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fatherLabel)
                                            .addComponent(motherLabel)
                                            .addComponent(boardLabel)
                                            .addComponent(groupLabel)
                                            .addComponent(rollLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearLabel)
                            .addComponent(typeLabel)
                            .addComponent(instituteLabel)
                            .addComponent(dobLabel)
                            .addComponent(regLevel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(gpaLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(examLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(examLabel)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rollLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(nameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fatherLabel)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(motherLabel)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boardLabel)
                            .addComponent(jLabel7))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(groupLabel)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel20)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(instituteLabel)))
                            .addComponent(jLabel21))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(typeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(yearLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regLevel)
                        .addGap(18, 18, 18)
                        .addComponent(dobLabel)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpaLabel))
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                new StudentFullResult().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JLabel boardLabel;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel examLabel;
    private javax.swing.JLabel fatherLabel;
    private javax.swing.JLabel gpaLabel;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JLabel instituteLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel motherLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel regLevel;
    private javax.swing.JLabel rollLabel;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
